### ISSUE TITLE
No way to contact team to join effort

### ISSUE THREAD

**Issue by IntangibleMatter** [SMW-Editor/smw-editor#35]
A few weeks ago I discovered this project and wanted to get involved. I both attempted to message this Discord ID and email the address from the readme, but ran into the following issues:

1. The Discord user doesn't accept messages from people not in the server, so Clyde auto-blocked me.
2. The email seems to be invalid, as the mail system it's a part of autoreplied saying that the email doesn't exist in the system.

As neither of the ways of contact expressed are usable, I am creating an issue proposing that a discord server or some equivalent system of communication is implemented, as there is at present little information available about this project, what has been completed, its design goals, or anything else, really.

Personally I have experience with UI design and wish to learn Rust, and I was contacted by someone on Twitter earlier who also expressed an interest in assisting with this project after I directed them here. They found a post of mine on the SMWCentral forums and messaged me on Twitter before finding this project because there is very little footprint. I and many others would be happy to help, we just need direction, and communication is vital for that.

**Comment by Adanos020** [comment]
Hey, thanks for bringing this up. The contact details were indeed out of date, I've just updated them in the readme. Feel free to reach out using those.
