### ISSUE TITLE
unwrap error on 16x16 tiles

### ISSUE THREAD

**Issue by romw314** [SMW-Editor/smw-editor#36]
## Description
When I open SMWE, create a new project, open *Tools* -> *16x16 tiles*, click *+* on level number until it's 0060 and click *+* again, it creates a panic like this:
```
thread 'main' panicked at smwe-rom\src\graphics\mod.rs:110:82:
called `Result::unwrap()` on an `Err` value: TileFromWramError(AddrSnes(0x7EB440))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\smw-editor.exe` (exit code: 101)
```

## Screen recording
![SMW-EDITOR-PANIC-UNWRAP-16x16](https://github.com/SMW-Editor/smw-editor/assets/106016361/18534ea3-a2ff-44bc-a5d3-9b41931aa9e0)

**Comment by Adanos020** [comment]
Hi, the 16x16 tiles window won't end up in the final editor, it was only supposed to help me see if I was decoding the graphics data correctly and it will not be worked on any further.

Ongoing development currently happens on the [`level`](https://github.com/SMW-Editor/smw-editor/tree/level) branch where we use a different rendering method (using an SNES emulator) anyway.
